const cityArray = [
    "New York",
    "Los Angeles",
    "Chicago",
    "Miami",
    "Dallas",
    "Houston",
    "Philadelphia",
    "Atlanta",
    "Washington",
    "Boston",
    "Phoenix",
    "Detroit",
    "Seattle",
    "San Francisco",
    "San Diego",
    "Minneapolis",
    "Brooklyn",
    "Tampa",
    "Denver",
    "Queens",
    "Baltimore",
    "Las Vegas",
    "St. Louis",
    "Portland",
    "Riverside",
    "Orlando",
    "Sacramento",
    "San Juan",
    "San Antonio",
    "San Jose",
    "Pittsburgh",
    "Cincinnati",
    "Manhattan",
    "Cleveland",
    "Indianapolis",
    "Austin",
    "Kansas City",
    "Columbus",
    "Charlotte",
    "Virginia Beach",
    "Bronx",
    "Milwaukee",
    "Providence",
    "Jacksonville",
    "Salt Lake City",
    "Nashville",
    "Raleigh",
    "Memphis",
    "Louisville",
    "Richmond"
];

export default cityArray;